/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MapaCalendar {
    }
    interface MapaDashboard {
    }
    interface MapaDiary {
    }
    interface MapaDocuments {
    }
    interface MapaExplore {
    }
    interface MapaFamilyStatus {
    }
    interface MapaHeader {
        "headline"?: string;
    }
    interface MapaIcon {
    }
    interface MapaIconLogo {
    }
    interface MapaKidsCreate {
    }
    interface MapaMediation {
    }
    interface MapaProfile {
        "name": string;
    }
    interface MapaProfileCreate {
    }
    interface MapaRoot {
    }
    interface MapaRouter {
    }
    interface MapaWelcome {
    }
}
declare global {
    interface HTMLMapaCalendarElement extends Components.MapaCalendar, HTMLStencilElement {
    }
    var HTMLMapaCalendarElement: {
        prototype: HTMLMapaCalendarElement;
        new (): HTMLMapaCalendarElement;
    };
    interface HTMLMapaDashboardElement extends Components.MapaDashboard, HTMLStencilElement {
    }
    var HTMLMapaDashboardElement: {
        prototype: HTMLMapaDashboardElement;
        new (): HTMLMapaDashboardElement;
    };
    interface HTMLMapaDiaryElement extends Components.MapaDiary, HTMLStencilElement {
    }
    var HTMLMapaDiaryElement: {
        prototype: HTMLMapaDiaryElement;
        new (): HTMLMapaDiaryElement;
    };
    interface HTMLMapaDocumentsElement extends Components.MapaDocuments, HTMLStencilElement {
    }
    var HTMLMapaDocumentsElement: {
        prototype: HTMLMapaDocumentsElement;
        new (): HTMLMapaDocumentsElement;
    };
    interface HTMLMapaExploreElement extends Components.MapaExplore, HTMLStencilElement {
    }
    var HTMLMapaExploreElement: {
        prototype: HTMLMapaExploreElement;
        new (): HTMLMapaExploreElement;
    };
    interface HTMLMapaFamilyStatusElement extends Components.MapaFamilyStatus, HTMLStencilElement {
    }
    var HTMLMapaFamilyStatusElement: {
        prototype: HTMLMapaFamilyStatusElement;
        new (): HTMLMapaFamilyStatusElement;
    };
    interface HTMLMapaHeaderElement extends Components.MapaHeader, HTMLStencilElement {
    }
    var HTMLMapaHeaderElement: {
        prototype: HTMLMapaHeaderElement;
        new (): HTMLMapaHeaderElement;
    };
    interface HTMLMapaIconElement extends Components.MapaIcon, HTMLStencilElement {
    }
    var HTMLMapaIconElement: {
        prototype: HTMLMapaIconElement;
        new (): HTMLMapaIconElement;
    };
    interface HTMLMapaIconLogoElement extends Components.MapaIconLogo, HTMLStencilElement {
    }
    var HTMLMapaIconLogoElement: {
        prototype: HTMLMapaIconLogoElement;
        new (): HTMLMapaIconLogoElement;
    };
    interface HTMLMapaKidsCreateElement extends Components.MapaKidsCreate, HTMLStencilElement {
    }
    var HTMLMapaKidsCreateElement: {
        prototype: HTMLMapaKidsCreateElement;
        new (): HTMLMapaKidsCreateElement;
    };
    interface HTMLMapaMediationElement extends Components.MapaMediation, HTMLStencilElement {
    }
    var HTMLMapaMediationElement: {
        prototype: HTMLMapaMediationElement;
        new (): HTMLMapaMediationElement;
    };
    interface HTMLMapaProfileElement extends Components.MapaProfile, HTMLStencilElement {
    }
    var HTMLMapaProfileElement: {
        prototype: HTMLMapaProfileElement;
        new (): HTMLMapaProfileElement;
    };
    interface HTMLMapaProfileCreateElement extends Components.MapaProfileCreate, HTMLStencilElement {
    }
    var HTMLMapaProfileCreateElement: {
        prototype: HTMLMapaProfileCreateElement;
        new (): HTMLMapaProfileCreateElement;
    };
    interface HTMLMapaRootElement extends Components.MapaRoot, HTMLStencilElement {
    }
    var HTMLMapaRootElement: {
        prototype: HTMLMapaRootElement;
        new (): HTMLMapaRootElement;
    };
    interface HTMLMapaRouterElement extends Components.MapaRouter, HTMLStencilElement {
    }
    var HTMLMapaRouterElement: {
        prototype: HTMLMapaRouterElement;
        new (): HTMLMapaRouterElement;
    };
    interface HTMLMapaWelcomeElement extends Components.MapaWelcome, HTMLStencilElement {
    }
    var HTMLMapaWelcomeElement: {
        prototype: HTMLMapaWelcomeElement;
        new (): HTMLMapaWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "mapa-calendar": HTMLMapaCalendarElement;
        "mapa-dashboard": HTMLMapaDashboardElement;
        "mapa-diary": HTMLMapaDiaryElement;
        "mapa-documents": HTMLMapaDocumentsElement;
        "mapa-explore": HTMLMapaExploreElement;
        "mapa-family-status": HTMLMapaFamilyStatusElement;
        "mapa-header": HTMLMapaHeaderElement;
        "mapa-icon": HTMLMapaIconElement;
        "mapa-icon-logo": HTMLMapaIconLogoElement;
        "mapa-kids-create": HTMLMapaKidsCreateElement;
        "mapa-mediation": HTMLMapaMediationElement;
        "mapa-profile": HTMLMapaProfileElement;
        "mapa-profile-create": HTMLMapaProfileCreateElement;
        "mapa-root": HTMLMapaRootElement;
        "mapa-router": HTMLMapaRouterElement;
        "mapa-welcome": HTMLMapaWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface MapaCalendar {
    }
    interface MapaDashboard {
    }
    interface MapaDiary {
    }
    interface MapaDocuments {
    }
    interface MapaExplore {
    }
    interface MapaFamilyStatus {
    }
    interface MapaHeader {
        "headline"?: string;
    }
    interface MapaIcon {
    }
    interface MapaIconLogo {
    }
    interface MapaKidsCreate {
    }
    interface MapaMediation {
    }
    interface MapaProfile {
        "name"?: string;
    }
    interface MapaProfileCreate {
    }
    interface MapaRoot {
    }
    interface MapaRouter {
    }
    interface MapaWelcome {
    }
    interface IntrinsicElements {
        "mapa-calendar": MapaCalendar;
        "mapa-dashboard": MapaDashboard;
        "mapa-diary": MapaDiary;
        "mapa-documents": MapaDocuments;
        "mapa-explore": MapaExplore;
        "mapa-family-status": MapaFamilyStatus;
        "mapa-header": MapaHeader;
        "mapa-icon": MapaIcon;
        "mapa-icon-logo": MapaIconLogo;
        "mapa-kids-create": MapaKidsCreate;
        "mapa-mediation": MapaMediation;
        "mapa-profile": MapaProfile;
        "mapa-profile-create": MapaProfileCreate;
        "mapa-root": MapaRoot;
        "mapa-router": MapaRouter;
        "mapa-welcome": MapaWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mapa-calendar": LocalJSX.MapaCalendar & JSXBase.HTMLAttributes<HTMLMapaCalendarElement>;
            "mapa-dashboard": LocalJSX.MapaDashboard & JSXBase.HTMLAttributes<HTMLMapaDashboardElement>;
            "mapa-diary": LocalJSX.MapaDiary & JSXBase.HTMLAttributes<HTMLMapaDiaryElement>;
            "mapa-documents": LocalJSX.MapaDocuments & JSXBase.HTMLAttributes<HTMLMapaDocumentsElement>;
            "mapa-explore": LocalJSX.MapaExplore & JSXBase.HTMLAttributes<HTMLMapaExploreElement>;
            "mapa-family-status": LocalJSX.MapaFamilyStatus & JSXBase.HTMLAttributes<HTMLMapaFamilyStatusElement>;
            "mapa-header": LocalJSX.MapaHeader & JSXBase.HTMLAttributes<HTMLMapaHeaderElement>;
            "mapa-icon": LocalJSX.MapaIcon & JSXBase.HTMLAttributes<HTMLMapaIconElement>;
            "mapa-icon-logo": LocalJSX.MapaIconLogo & JSXBase.HTMLAttributes<HTMLMapaIconLogoElement>;
            "mapa-kids-create": LocalJSX.MapaKidsCreate & JSXBase.HTMLAttributes<HTMLMapaKidsCreateElement>;
            "mapa-mediation": LocalJSX.MapaMediation & JSXBase.HTMLAttributes<HTMLMapaMediationElement>;
            "mapa-profile": LocalJSX.MapaProfile & JSXBase.HTMLAttributes<HTMLMapaProfileElement>;
            "mapa-profile-create": LocalJSX.MapaProfileCreate & JSXBase.HTMLAttributes<HTMLMapaProfileCreateElement>;
            "mapa-root": LocalJSX.MapaRoot & JSXBase.HTMLAttributes<HTMLMapaRootElement>;
            "mapa-router": LocalJSX.MapaRouter & JSXBase.HTMLAttributes<HTMLMapaRouterElement>;
            "mapa-welcome": LocalJSX.MapaWelcome & JSXBase.HTMLAttributes<HTMLMapaWelcomeElement>;
        }
    }
}
