/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MapaCalendar {
    }
    interface MapaColorPicker {
        "colors": string[];
        "selected"?: string;
    }
    interface MapaDashboard {
    }
    interface MapaDiary {
    }
    interface MapaDocuments {
    }
    interface MapaExplore {
    }
    interface MapaFamilyState {
        "active": boolean;
        "status": "together" | "divorced" | "patched" | "single";
    }
    interface MapaFamilyStatus {
    }
    interface MapaGenderSelect {
        "selected"?: "female" | "male";
    }
    interface MapaHeader {
        "headline"?: string;
    }
    interface MapaIcon {
    }
    interface MapaIconFamily {
        "status": "together" | "divorced" | "patched" | "single";
    }
    interface MapaIconGender {
        "gender": "female" | "male";
    }
    interface MapaIconHome {
    }
    interface MapaIconIdea {
    }
    interface MapaIconKite {
    }
    interface MapaIconLogo {
    }
    interface MapaKidsCreate {
    }
    interface MapaLogin {
    }
    interface MapaMain {
    }
    interface MapaMediation {
    }
    interface MapaProfile {
        "name": string;
    }
    interface MapaProfileCreate {
    }
    interface MapaRoot {
    }
    interface MapaRouter {
    }
    interface MapaWelcome {
    }
}
declare global {
    interface HTMLMapaCalendarElement extends Components.MapaCalendar, HTMLStencilElement {
    }
    var HTMLMapaCalendarElement: {
        prototype: HTMLMapaCalendarElement;
        new (): HTMLMapaCalendarElement;
    };
    interface HTMLMapaColorPickerElement extends Components.MapaColorPicker, HTMLStencilElement {
    }
    var HTMLMapaColorPickerElement: {
        prototype: HTMLMapaColorPickerElement;
        new (): HTMLMapaColorPickerElement;
    };
    interface HTMLMapaDashboardElement extends Components.MapaDashboard, HTMLStencilElement {
    }
    var HTMLMapaDashboardElement: {
        prototype: HTMLMapaDashboardElement;
        new (): HTMLMapaDashboardElement;
    };
    interface HTMLMapaDiaryElement extends Components.MapaDiary, HTMLStencilElement {
    }
    var HTMLMapaDiaryElement: {
        prototype: HTMLMapaDiaryElement;
        new (): HTMLMapaDiaryElement;
    };
    interface HTMLMapaDocumentsElement extends Components.MapaDocuments, HTMLStencilElement {
    }
    var HTMLMapaDocumentsElement: {
        prototype: HTMLMapaDocumentsElement;
        new (): HTMLMapaDocumentsElement;
    };
    interface HTMLMapaExploreElement extends Components.MapaExplore, HTMLStencilElement {
    }
    var HTMLMapaExploreElement: {
        prototype: HTMLMapaExploreElement;
        new (): HTMLMapaExploreElement;
    };
    interface HTMLMapaFamilyStateElement extends Components.MapaFamilyState, HTMLStencilElement {
    }
    var HTMLMapaFamilyStateElement: {
        prototype: HTMLMapaFamilyStateElement;
        new (): HTMLMapaFamilyStateElement;
    };
    interface HTMLMapaFamilyStatusElement extends Components.MapaFamilyStatus, HTMLStencilElement {
    }
    var HTMLMapaFamilyStatusElement: {
        prototype: HTMLMapaFamilyStatusElement;
        new (): HTMLMapaFamilyStatusElement;
    };
    interface HTMLMapaGenderSelectElement extends Components.MapaGenderSelect, HTMLStencilElement {
    }
    var HTMLMapaGenderSelectElement: {
        prototype: HTMLMapaGenderSelectElement;
        new (): HTMLMapaGenderSelectElement;
    };
    interface HTMLMapaHeaderElement extends Components.MapaHeader, HTMLStencilElement {
    }
    var HTMLMapaHeaderElement: {
        prototype: HTMLMapaHeaderElement;
        new (): HTMLMapaHeaderElement;
    };
    interface HTMLMapaIconElement extends Components.MapaIcon, HTMLStencilElement {
    }
    var HTMLMapaIconElement: {
        prototype: HTMLMapaIconElement;
        new (): HTMLMapaIconElement;
    };
    interface HTMLMapaIconFamilyElement extends Components.MapaIconFamily, HTMLStencilElement {
    }
    var HTMLMapaIconFamilyElement: {
        prototype: HTMLMapaIconFamilyElement;
        new (): HTMLMapaIconFamilyElement;
    };
    interface HTMLMapaIconGenderElement extends Components.MapaIconGender, HTMLStencilElement {
    }
    var HTMLMapaIconGenderElement: {
        prototype: HTMLMapaIconGenderElement;
        new (): HTMLMapaIconGenderElement;
    };
    interface HTMLMapaIconHomeElement extends Components.MapaIconHome, HTMLStencilElement {
    }
    var HTMLMapaIconHomeElement: {
        prototype: HTMLMapaIconHomeElement;
        new (): HTMLMapaIconHomeElement;
    };
    interface HTMLMapaIconIdeaElement extends Components.MapaIconIdea, HTMLStencilElement {
    }
    var HTMLMapaIconIdeaElement: {
        prototype: HTMLMapaIconIdeaElement;
        new (): HTMLMapaIconIdeaElement;
    };
    interface HTMLMapaIconKiteElement extends Components.MapaIconKite, HTMLStencilElement {
    }
    var HTMLMapaIconKiteElement: {
        prototype: HTMLMapaIconKiteElement;
        new (): HTMLMapaIconKiteElement;
    };
    interface HTMLMapaIconLogoElement extends Components.MapaIconLogo, HTMLStencilElement {
    }
    var HTMLMapaIconLogoElement: {
        prototype: HTMLMapaIconLogoElement;
        new (): HTMLMapaIconLogoElement;
    };
    interface HTMLMapaKidsCreateElement extends Components.MapaKidsCreate, HTMLStencilElement {
    }
    var HTMLMapaKidsCreateElement: {
        prototype: HTMLMapaKidsCreateElement;
        new (): HTMLMapaKidsCreateElement;
    };
    interface HTMLMapaLoginElement extends Components.MapaLogin, HTMLStencilElement {
    }
    var HTMLMapaLoginElement: {
        prototype: HTMLMapaLoginElement;
        new (): HTMLMapaLoginElement;
    };
    interface HTMLMapaMainElement extends Components.MapaMain, HTMLStencilElement {
    }
    var HTMLMapaMainElement: {
        prototype: HTMLMapaMainElement;
        new (): HTMLMapaMainElement;
    };
    interface HTMLMapaMediationElement extends Components.MapaMediation, HTMLStencilElement {
    }
    var HTMLMapaMediationElement: {
        prototype: HTMLMapaMediationElement;
        new (): HTMLMapaMediationElement;
    };
    interface HTMLMapaProfileElement extends Components.MapaProfile, HTMLStencilElement {
    }
    var HTMLMapaProfileElement: {
        prototype: HTMLMapaProfileElement;
        new (): HTMLMapaProfileElement;
    };
    interface HTMLMapaProfileCreateElement extends Components.MapaProfileCreate, HTMLStencilElement {
    }
    var HTMLMapaProfileCreateElement: {
        prototype: HTMLMapaProfileCreateElement;
        new (): HTMLMapaProfileCreateElement;
    };
    interface HTMLMapaRootElement extends Components.MapaRoot, HTMLStencilElement {
    }
    var HTMLMapaRootElement: {
        prototype: HTMLMapaRootElement;
        new (): HTMLMapaRootElement;
    };
    interface HTMLMapaRouterElement extends Components.MapaRouter, HTMLStencilElement {
    }
    var HTMLMapaRouterElement: {
        prototype: HTMLMapaRouterElement;
        new (): HTMLMapaRouterElement;
    };
    interface HTMLMapaWelcomeElement extends Components.MapaWelcome, HTMLStencilElement {
    }
    var HTMLMapaWelcomeElement: {
        prototype: HTMLMapaWelcomeElement;
        new (): HTMLMapaWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "mapa-calendar": HTMLMapaCalendarElement;
        "mapa-color-picker": HTMLMapaColorPickerElement;
        "mapa-dashboard": HTMLMapaDashboardElement;
        "mapa-diary": HTMLMapaDiaryElement;
        "mapa-documents": HTMLMapaDocumentsElement;
        "mapa-explore": HTMLMapaExploreElement;
        "mapa-family-state": HTMLMapaFamilyStateElement;
        "mapa-family-status": HTMLMapaFamilyStatusElement;
        "mapa-gender-select": HTMLMapaGenderSelectElement;
        "mapa-header": HTMLMapaHeaderElement;
        "mapa-icon": HTMLMapaIconElement;
        "mapa-icon-family": HTMLMapaIconFamilyElement;
        "mapa-icon-gender": HTMLMapaIconGenderElement;
        "mapa-icon-home": HTMLMapaIconHomeElement;
        "mapa-icon-idea": HTMLMapaIconIdeaElement;
        "mapa-icon-kite": HTMLMapaIconKiteElement;
        "mapa-icon-logo": HTMLMapaIconLogoElement;
        "mapa-kids-create": HTMLMapaKidsCreateElement;
        "mapa-login": HTMLMapaLoginElement;
        "mapa-main": HTMLMapaMainElement;
        "mapa-mediation": HTMLMapaMediationElement;
        "mapa-profile": HTMLMapaProfileElement;
        "mapa-profile-create": HTMLMapaProfileCreateElement;
        "mapa-root": HTMLMapaRootElement;
        "mapa-router": HTMLMapaRouterElement;
        "mapa-welcome": HTMLMapaWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface MapaCalendar {
    }
    interface MapaColorPicker {
        "colors"?: string[];
        "onColored"?: (event: CustomEvent<string>) => void;
        "selected"?: string;
    }
    interface MapaDashboard {
    }
    interface MapaDiary {
    }
    interface MapaDocuments {
    }
    interface MapaExplore {
    }
    interface MapaFamilyState {
        "active"?: boolean;
        "status"?: "together" | "divorced" | "patched" | "single";
    }
    interface MapaFamilyStatus {
    }
    interface MapaGenderSelect {
        "onGendered"?: (event: CustomEvent<"female" | "male">) => void;
        "selected"?: "female" | "male";
    }
    interface MapaHeader {
        "headline"?: string;
    }
    interface MapaIcon {
    }
    interface MapaIconFamily {
        "status"?: "together" | "divorced" | "patched" | "single";
    }
    interface MapaIconGender {
        "gender"?: "female" | "male";
    }
    interface MapaIconHome {
    }
    interface MapaIconIdea {
    }
    interface MapaIconKite {
    }
    interface MapaIconLogo {
    }
    interface MapaKidsCreate {
    }
    interface MapaLogin {
    }
    interface MapaMain {
    }
    interface MapaMediation {
    }
    interface MapaProfile {
        "name"?: string;
    }
    interface MapaProfileCreate {
    }
    interface MapaRoot {
    }
    interface MapaRouter {
    }
    interface MapaWelcome {
    }
    interface IntrinsicElements {
        "mapa-calendar": MapaCalendar;
        "mapa-color-picker": MapaColorPicker;
        "mapa-dashboard": MapaDashboard;
        "mapa-diary": MapaDiary;
        "mapa-documents": MapaDocuments;
        "mapa-explore": MapaExplore;
        "mapa-family-state": MapaFamilyState;
        "mapa-family-status": MapaFamilyStatus;
        "mapa-gender-select": MapaGenderSelect;
        "mapa-header": MapaHeader;
        "mapa-icon": MapaIcon;
        "mapa-icon-family": MapaIconFamily;
        "mapa-icon-gender": MapaIconGender;
        "mapa-icon-home": MapaIconHome;
        "mapa-icon-idea": MapaIconIdea;
        "mapa-icon-kite": MapaIconKite;
        "mapa-icon-logo": MapaIconLogo;
        "mapa-kids-create": MapaKidsCreate;
        "mapa-login": MapaLogin;
        "mapa-main": MapaMain;
        "mapa-mediation": MapaMediation;
        "mapa-profile": MapaProfile;
        "mapa-profile-create": MapaProfileCreate;
        "mapa-root": MapaRoot;
        "mapa-router": MapaRouter;
        "mapa-welcome": MapaWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mapa-calendar": LocalJSX.MapaCalendar & JSXBase.HTMLAttributes<HTMLMapaCalendarElement>;
            "mapa-color-picker": LocalJSX.MapaColorPicker & JSXBase.HTMLAttributes<HTMLMapaColorPickerElement>;
            "mapa-dashboard": LocalJSX.MapaDashboard & JSXBase.HTMLAttributes<HTMLMapaDashboardElement>;
            "mapa-diary": LocalJSX.MapaDiary & JSXBase.HTMLAttributes<HTMLMapaDiaryElement>;
            "mapa-documents": LocalJSX.MapaDocuments & JSXBase.HTMLAttributes<HTMLMapaDocumentsElement>;
            "mapa-explore": LocalJSX.MapaExplore & JSXBase.HTMLAttributes<HTMLMapaExploreElement>;
            "mapa-family-state": LocalJSX.MapaFamilyState & JSXBase.HTMLAttributes<HTMLMapaFamilyStateElement>;
            "mapa-family-status": LocalJSX.MapaFamilyStatus & JSXBase.HTMLAttributes<HTMLMapaFamilyStatusElement>;
            "mapa-gender-select": LocalJSX.MapaGenderSelect & JSXBase.HTMLAttributes<HTMLMapaGenderSelectElement>;
            "mapa-header": LocalJSX.MapaHeader & JSXBase.HTMLAttributes<HTMLMapaHeaderElement>;
            "mapa-icon": LocalJSX.MapaIcon & JSXBase.HTMLAttributes<HTMLMapaIconElement>;
            "mapa-icon-family": LocalJSX.MapaIconFamily & JSXBase.HTMLAttributes<HTMLMapaIconFamilyElement>;
            "mapa-icon-gender": LocalJSX.MapaIconGender & JSXBase.HTMLAttributes<HTMLMapaIconGenderElement>;
            "mapa-icon-home": LocalJSX.MapaIconHome & JSXBase.HTMLAttributes<HTMLMapaIconHomeElement>;
            "mapa-icon-idea": LocalJSX.MapaIconIdea & JSXBase.HTMLAttributes<HTMLMapaIconIdeaElement>;
            "mapa-icon-kite": LocalJSX.MapaIconKite & JSXBase.HTMLAttributes<HTMLMapaIconKiteElement>;
            "mapa-icon-logo": LocalJSX.MapaIconLogo & JSXBase.HTMLAttributes<HTMLMapaIconLogoElement>;
            "mapa-kids-create": LocalJSX.MapaKidsCreate & JSXBase.HTMLAttributes<HTMLMapaKidsCreateElement>;
            "mapa-login": LocalJSX.MapaLogin & JSXBase.HTMLAttributes<HTMLMapaLoginElement>;
            "mapa-main": LocalJSX.MapaMain & JSXBase.HTMLAttributes<HTMLMapaMainElement>;
            "mapa-mediation": LocalJSX.MapaMediation & JSXBase.HTMLAttributes<HTMLMapaMediationElement>;
            "mapa-profile": LocalJSX.MapaProfile & JSXBase.HTMLAttributes<HTMLMapaProfileElement>;
            "mapa-profile-create": LocalJSX.MapaProfileCreate & JSXBase.HTMLAttributes<HTMLMapaProfileCreateElement>;
            "mapa-root": LocalJSX.MapaRoot & JSXBase.HTMLAttributes<HTMLMapaRootElement>;
            "mapa-router": LocalJSX.MapaRouter & JSXBase.HTMLAttributes<HTMLMapaRouterElement>;
            "mapa-welcome": LocalJSX.MapaWelcome & JSXBase.HTMLAttributes<HTMLMapaWelcomeElement>;
        }
    }
}
