# This is a basic workflow to help you get started with Actions

name: Deploy to Droplet

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/deploy-to-droplet-wip
    paths:
      - 'packages/backend/**'
      - '.github/workflows/deploy-to-droplet.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Clone
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_KEY }}
        script: |
          git clone git@github.com:mapa-app/source.git -b master mapa-app-${{ $github.sha }}
